# Generated by Django 4.2.16 on 2024-12-16 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerlogin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='usuario_defecto.jpg', upload_to='', verbose_name='Imagen de perfil'),
        ),
    ]
