# Generated by Django 4.2.16 on 2024-12-16 06:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registerlogin', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/ddfknxf4e/image/upload/v1734327910/gy4npmb6nrllx2iup502.jpg', max_length=255, verbose_name='image'),
        ),
    ]
