# Generated by Django 4.2.16 on 2024-12-07 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_rut', models.CharField(max_length=12)),
                ('employee_name', models.CharField(max_length=50)),
                ('employee_contactnumber', models.CharField(max_length=20)),
                ('employee_email', models.CharField(max_length=50)),
                ('employee_password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('product_image', models.ImageField(upload_to='')),
                ('product_stock', models.PositiveIntegerField()),
                ('product_price', models.PositiveIntegerField()),
                ('product_desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='storage',
            fields=[
                ('storage_id', models.AutoField(primary_key=True, serialize=False)),
                ('storage_address', models.CharField(max_length=50)),
                ('storage_schedule', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='removeMovements',
            fields=[
                ('removemov_id', models.AutoField(primary_key=True, serialize=False)),
                ('removemov_date', models.DateTimeField(auto_now_add=True)),
                ('removemov_prodQuantity', models.PositiveIntegerField()),
                ('incharge', models.ManyToManyField(to='crud.employee', verbose_name='employee')),
                ('product', models.ManyToManyField(to='crud.product', verbose_name='product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='storage',
            field=models.ManyToManyField(to='crud.storage', verbose_name='storage'),
        ),
        migrations.CreateModel(
            name='addMovements',
            fields=[
                ('addmov_id', models.AutoField(primary_key=True, serialize=False)),
                ('addmov_date', models.DateTimeField(auto_now_add=True)),
                ('addmov_prodQuantity', models.PositiveIntegerField()),
                ('incharge', models.ManyToManyField(to='crud.employee', verbose_name='employee')),
                ('product', models.ManyToManyField(to='crud.product', verbose_name='product')),
            ],
        ),
    ]
