# Generated by Django 4.2.16 on 2024-12-10 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addmovements',
            name='incharge',
        ),
        migrations.RemoveField(
            model_name='addmovements',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='storage',
        ),
        migrations.RemoveField(
            model_name='removemovements',
            name='incharge',
        ),
        migrations.RemoveField(
            model_name='removemovements',
            name='product',
        ),
        migrations.AddField(
            model_name='addmovements',
            name='incharge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crud.employee', verbose_name='employee'),
        ),
        migrations.AddField(
            model_name='addmovements',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crud.product', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='product',
            name='storage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crud.storage', verbose_name='storage'),
        ),
        migrations.AddField(
            model_name='removemovements',
            name='incharge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crud.employee', verbose_name='employee'),
        ),
        migrations.AddField(
            model_name='removemovements',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crud.product', verbose_name='product'),
        ),
    ]
