# Generated by Django 4.2.16 on 2024-12-16 06:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_alter_addmovements_incharge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/ddfknxf4e/image/upload/v1734327909/zzpxq71qifkzk0nlmyxd.jpg', max_length=255, verbose_name='image'),
        ),
    ]
