# Generated by Django 4.2.16 on 2024-12-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_alter_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.FileField(default='https://res.cloudinary.com/ddfknxf4e/image/upload/v1734327909/zzpxq71qifkzk0nlmyxd.jpg', upload_to=''),
        ),
    ]
